version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: db
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - zbx-nn
  zbx:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    container_name: zbx
    ports:
      - "10051:10051"
      - "8080:8080"
    networks:
      - zbx-nn
volumes:
  db:
    driver: local
networks:
  zbx-nn:
    driver: bridge